// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @RouterService, @Service, @Inject, @InjectCfgValue, @Route

package memory

import (
	"github.com/primadi/lokstra/lokstra_registry"
)

// Auto-register on package import
func init() {
	RegisterInMemoryStore()
}

// ============================================================
// FILE: policy_Store.go
// ============================================================

// RegisterInMemoryStore registers the in-memory-policy-store with the registry
// Auto-generated from annotations:
//   - @Service name="in-memory-policy-store"
func RegisterInMemoryStore() {
	lokstra_registry.RegisterLazyService("in-memory-policy-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &InMemoryStore{
		}
		
		// Call Init() for post-initialization
		if err := svc.Init(); err != nil {
			panic("failed to initialize in-memory-policy-store: " + err.Error())
		}
		
		return svc
	}, map[string]any{
	})
}


