// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @RouterService, @Service, @Inject, @InjectCfgValue, @Route

package application

import (
	"github.com/primadi/lokstra/core/deploy"
	"github.com/primadi/lokstra/core/proxy"
	"github.com/primadi/lokstra/lokstra_registry"
	token "github.com/primadi/lokstra-auth/token"
	request "github.com/primadi/lokstra/core/request"
)

// Auto-register on package import
func init() {
	RegisterTokenService()
}

// ============================================================
// FILE: token_service.go
// ============================================================

// TokenServiceRemote implements TokenServiceInterface with HTTP proxy
// Auto-generated from TokenService interface methods
type TokenServiceRemote struct {
	proxyService *proxy.Service
}

// NewTokenServiceRemote creates a new remote token-service proxy
func NewTokenServiceRemote(proxyService *proxy.Service) *TokenServiceRemote {
	return &TokenServiceRemote{
		proxyService: proxyService,
	}
}

// Introspect via HTTP
// Generated from: @Route "POST /introspect"
func (s *TokenServiceRemote) Introspect(p *request.Context) (*IntrospectResponse, error) {
	return proxy.CallWithData[*IntrospectResponse](s.proxyService, "Introspect", p)
}

// Refresh via HTTP
// Generated from: @Route "POST /refresh"
func (s *TokenServiceRemote) Refresh(p *request.Context) (*RefreshResponse, error) {
	return proxy.CallWithData[*RefreshResponse](s.proxyService, "Refresh", p)
}

// Revoke via HTTP
// Generated from: @Route "POST /revoke"
func (s *TokenServiceRemote) Revoke(p *request.Context) (*RevokeResponse, error) {
	return proxy.CallWithData[*RevokeResponse](s.proxyService, "Revoke", p)
}

// Validate via HTTP
// Generated from: @Route "POST /validate"
func (s *TokenServiceRemote) Validate(p *request.Context) (*ValidateResponse, error) {
	return proxy.CallWithData[*ValidateResponse](s.proxyService, "Validate", p)
}


func TokenServiceFactory(deps map[string]any, config map[string]any) any {
	svc := &TokenService{
		TokenManager: deps["token-manager"].(token.TokenManager),
	}
	
	return svc
}

// TokenServiceRemoteFactory creates a remote HTTP client for TokenServiceInterface
// Auto-generated from @RouterService annotation
func TokenServiceRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewTokenServiceRemote(proxyService)
}

// RegisterTokenService registers the token-service with the registry
// Auto-generated from annotations:
//   - @RouterService name="token-service", prefix="${api-auth-prefix:/api/auth}/token"
//   - @Inject annotations
//   - @Route annotations on methods
func RegisterTokenService() {
	// Register service type with router configuration
	lokstra_registry.RegisterRouterServiceType("token-service-factory",
		TokenServiceFactory,
		TokenServiceRemoteFactory,
		&deploy.ServiceTypeConfig{
			PathPrefix:  "${api-auth-prefix:/api/auth}/token",
			Middlewares: []string{ "recovery", "request_logger" },
			RouteOverrides: map[string]deploy.RouteConfig{
				"Introspect": {
					Path: "POST /introspect",
				},
				"Refresh": {
					Path: "POST /refresh",
				},
				"Revoke": {
					Path: "POST /revoke",
				},
				"Validate": {
					Path: "POST /validate",
				},
			},
		},
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("token-service",
		"token-service-factory",
		map[string]any{
			"depends-on": []string{ "token-manager", },
		})
}


