// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @RouterService, @Service, @Inject, @InjectCfgValue, @Route

package application

import (
	"github.com/primadi/lokstra/core/deploy"
	"github.com/primadi/lokstra/core/proxy"
	"github.com/primadi/lokstra/lokstra_registry"
	repository "github.com/primadi/lokstra-auth/infrastructure/repository"
	domain "github.com/primadi/lokstra-auth/rbac/domain"
	request "github.com/primadi/lokstra/core/request"
)

// Auto-register on package import
func init() {
	RegisterPermissionCompositionService()
	RegisterPermissionService()
	RegisterRolePermissionService()
	RegisterRoleService()
	RegisterUserPermissionService()
	RegisterUserRoleService()
}

// ============================================================
// FILE: permission_composition_service.go
// ============================================================

// PermissionCompositionServiceRemote implements PermissionCompositionServiceInterface with HTTP proxy
// Auto-generated from PermissionCompositionService interface methods
type PermissionCompositionServiceRemote struct {
	proxyService *proxy.Service
}

// NewPermissionCompositionServiceRemote creates a new remote permission-composition-service proxy
func NewPermissionCompositionServiceRemote(proxyService *proxy.Service) *PermissionCompositionServiceRemote {
	return &PermissionCompositionServiceRemote{
		proxyService: proxyService,
	}
}

// AddChildPermission via HTTP
// Generated from: @Route "POST /"
func (s *PermissionCompositionServiceRemote) AddChildPermission(p *request.Context) (*domain.PermissionComposition, error) {
	return proxy.CallWithData[*domain.PermissionComposition](s.proxyService, "AddChildPermission", p)
}

// GetEffectivePermissions via HTTP
// Generated from: @Route "GET /effective"
func (s *PermissionCompositionServiceRemote) GetEffectivePermissions(p *request.Context) (*EffectivePermissionsResponse, error) {
	return proxy.CallWithData[*EffectivePermissionsResponse](s.proxyService, "GetEffectivePermissions", p)
}

// ListCompositions via HTTP
// Generated from: @Route "GET /"
func (s *PermissionCompositionServiceRemote) ListCompositions(p *request.Context) ([]*domain.PermissionComposition, error) {
	return proxy.CallWithData[[]*domain.PermissionComposition](s.proxyService, "ListCompositions", p)
}

// RemoveChildPermission via HTTP
// Generated from: @Route "DELETE /{child_permission_id}"
func (s *PermissionCompositionServiceRemote) RemoveChildPermission(p *request.Context) error {
	return proxy.Call(s.proxyService, "RemoveChildPermission", p)
}


func PermissionCompositionServiceFactory(deps map[string]any, config map[string]any) any {
	svc := &PermissionCompositionService{
		CompositionStore: deps["permission-composition-store"].(repository.PermissionCompositionStore),
		PermissionStore: deps["permission-store"].(repository.PermissionStore),
	}
	
	return svc
}

// PermissionCompositionServiceRemoteFactory creates a remote HTTP client for PermissionCompositionServiceInterface
// Auto-generated from @RouterService annotation
func PermissionCompositionServiceRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewPermissionCompositionServiceRemote(proxyService)
}

// RegisterPermissionCompositionService registers the permission-composition-service with the registry
// Auto-generated from annotations:
//   - @RouterService name="permission-composition-service", prefix="${api-auth-prefix:/api/auth}/rbac/tenants/{tenant_id}/apps/{app_id}/permissions/{permission_id}/compositions"
//   - @Inject annotations
//   - @Route annotations on methods
func RegisterPermissionCompositionService() {
	// Register service type with router configuration
	lokstra_registry.RegisterRouterServiceType("permission-composition-service-factory",
		PermissionCompositionServiceFactory,
		PermissionCompositionServiceRemoteFactory,
		&deploy.ServiceTypeConfig{
			PathPrefix:  "${api-auth-prefix:/api/auth}/rbac/tenants/{tenant_id}/apps/{app_id}/permissions/{permission_id}/compositions",
			Middlewares: []string{ "recovery", "request_logger", "auth" },
			RouteOverrides: map[string]deploy.RouteConfig{
				"AddChildPermission": {
					Path: "POST /",
				},
				"GetEffectivePermissions": {
					Path: "GET /effective",
				},
				"ListCompositions": {
					Path: "GET /",
				},
				"RemoveChildPermission": {
					Path: "DELETE /{child_permission_id}",
				},
			},
		},
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("permission-composition-service",
		"permission-composition-service-factory",
		map[string]any{
			"depends-on": []string{ "permission-composition-store", "permission-store", },
		})
}


// ============================================================
// FILE: permission_service.go
// ============================================================

// PermissionServiceRemote implements PermissionServiceInterface with HTTP proxy
// Auto-generated from PermissionService interface methods
type PermissionServiceRemote struct {
	proxyService *proxy.Service
}

// NewPermissionServiceRemote creates a new remote permission-service proxy
func NewPermissionServiceRemote(proxyService *proxy.Service) *PermissionServiceRemote {
	return &PermissionServiceRemote{
		proxyService: proxyService,
	}
}

// CreatePermission via HTTP
// Generated from: @Route "POST /"
func (s *PermissionServiceRemote) CreatePermission(p *request.Context) (*domain.Permission, error) {
	return proxy.CallWithData[*domain.Permission](s.proxyService, "CreatePermission", p)
}

// DeletePermission via HTTP
// Generated from: @Route "DELETE /{permission_id}"
func (s *PermissionServiceRemote) DeletePermission(p *request.Context) error {
	return proxy.Call(s.proxyService, "DeletePermission", p)
}

// GetPermission via HTTP
// Generated from: @Route "GET /{permission_id}"
func (s *PermissionServiceRemote) GetPermission(p *request.Context) (*domain.Permission, error) {
	return proxy.CallWithData[*domain.Permission](s.proxyService, "GetPermission", p)
}

// ListPermissions via HTTP
// Generated from: @Route "GET /"
func (s *PermissionServiceRemote) ListPermissions(p *request.Context) ([]*domain.Permission, error) {
	return proxy.CallWithData[[]*domain.Permission](s.proxyService, "ListPermissions", p)
}

// UpdatePermission via HTTP
// Generated from: @Route "PUT /{permission_id}"
func (s *PermissionServiceRemote) UpdatePermission(p *request.Context) (*domain.Permission, error) {
	return proxy.CallWithData[*domain.Permission](s.proxyService, "UpdatePermission", p)
}


func PermissionServiceFactory(deps map[string]any, config map[string]any) any {
	svc := &PermissionService{
		PermissionStore: deps["permission-store"].(repository.PermissionStore),
	}
	
	return svc
}

// PermissionServiceRemoteFactory creates a remote HTTP client for PermissionServiceInterface
// Auto-generated from @RouterService annotation
func PermissionServiceRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewPermissionServiceRemote(proxyService)
}

// RegisterPermissionService registers the permission-service with the registry
// Auto-generated from annotations:
//   - @RouterService name="permission-service", prefix="${api-auth-prefix:/api/auth}/rbac/tenants/{tenant_id}/apps/{app_id}/permissions"
//   - @Inject annotations
//   - @Route annotations on methods
func RegisterPermissionService() {
	// Register service type with router configuration
	lokstra_registry.RegisterRouterServiceType("permission-service-factory",
		PermissionServiceFactory,
		PermissionServiceRemoteFactory,
		&deploy.ServiceTypeConfig{
			PathPrefix:  "${api-auth-prefix:/api/auth}/rbac/tenants/{tenant_id}/apps/{app_id}/permissions",
			Middlewares: []string{ "recovery", "request_logger", "auth" },
			RouteOverrides: map[string]deploy.RouteConfig{
				"CreatePermission": {
					Path: "POST /",
				},
				"DeletePermission": {
					Path: "DELETE /{permission_id}",
				},
				"GetPermission": {
					Path: "GET /{permission_id}",
				},
				"ListPermissions": {
					Path: "GET /",
				},
				"UpdatePermission": {
					Path: "PUT /{permission_id}",
				},
			},
		},
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("permission-service",
		"permission-service-factory",
		map[string]any{
			"depends-on": []string{ "permission-store", },
		})
}


// ============================================================
// FILE: role_permission_service.go
// ============================================================

// RolePermissionServiceRemote implements RolePermissionServiceInterface with HTTP proxy
// Auto-generated from RolePermissionService interface methods
type RolePermissionServiceRemote struct {
	proxyService *proxy.Service
}

// NewRolePermissionServiceRemote creates a new remote role-permission-service proxy
func NewRolePermissionServiceRemote(proxyService *proxy.Service) *RolePermissionServiceRemote {
	return &RolePermissionServiceRemote{
		proxyService: proxyService,
	}
}

// AssignPermissionToRole via HTTP
// Generated from: @Route "POST /"
func (s *RolePermissionServiceRemote) AssignPermissionToRole(p *request.Context) error {
	return proxy.Call(s.proxyService, "AssignPermissionToRole", p)
}

// ListRolePermissions via HTTP
// Generated from: @Route "GET /"
func (s *RolePermissionServiceRemote) ListRolePermissions(p *request.Context) ([]*domain.Permission, error) {
	return proxy.CallWithData[[]*domain.Permission](s.proxyService, "ListRolePermissions", p)
}

// RevokePermissionFromRole via HTTP
// Generated from: @Route "DELETE /{permission_id}"
func (s *RolePermissionServiceRemote) RevokePermissionFromRole(p *request.Context) error {
	return proxy.Call(s.proxyService, "RevokePermissionFromRole", p)
}


func RolePermissionServiceFactory(deps map[string]any, config map[string]any) any {
	svc := &RolePermissionService{
		PermissionStore: deps["permission-store"].(repository.PermissionStore),
		RolePermissionStore: deps["role-permission-store"].(repository.RolePermissionStore),
		RoleStore: deps["role-store"].(repository.RoleStore),
	}
	
	return svc
}

// RolePermissionServiceRemoteFactory creates a remote HTTP client for RolePermissionServiceInterface
// Auto-generated from @RouterService annotation
func RolePermissionServiceRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewRolePermissionServiceRemote(proxyService)
}

// RegisterRolePermissionService registers the role-permission-service with the registry
// Auto-generated from annotations:
//   - @RouterService name="role-permission-service", prefix="${api-auth-prefix:/api/auth}/rbac/tenants/{tenant_id}/apps/{app_id}/roles/{role_id}/permissions"
//   - @Inject annotations
//   - @Route annotations on methods
func RegisterRolePermissionService() {
	// Register service type with router configuration
	lokstra_registry.RegisterRouterServiceType("role-permission-service-factory",
		RolePermissionServiceFactory,
		RolePermissionServiceRemoteFactory,
		&deploy.ServiceTypeConfig{
			PathPrefix:  "${api-auth-prefix:/api/auth}/rbac/tenants/{tenant_id}/apps/{app_id}/roles/{role_id}/permissions",
			Middlewares: []string{ "recovery", "request_logger", "auth" },
			RouteOverrides: map[string]deploy.RouteConfig{
				"AssignPermissionToRole": {
					Path: "POST /",
				},
				"ListRolePermissions": {
					Path: "GET /",
				},
				"RevokePermissionFromRole": {
					Path: "DELETE /{permission_id}",
				},
			},
		},
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("role-permission-service",
		"role-permission-service-factory",
		map[string]any{
			"depends-on": []string{ "permission-store", "role-permission-store", "role-store", },
		})
}


// ============================================================
// FILE: role_service.go
// ============================================================

// RoleServiceRemote implements RoleServiceInterface with HTTP proxy
// Auto-generated from RoleService interface methods
type RoleServiceRemote struct {
	proxyService *proxy.Service
}

// NewRoleServiceRemote creates a new remote role-service proxy
func NewRoleServiceRemote(proxyService *proxy.Service) *RoleServiceRemote {
	return &RoleServiceRemote{
		proxyService: proxyService,
	}
}

// CreateRole via HTTP
// Generated from: @Route "POST /"
func (s *RoleServiceRemote) CreateRole(p *request.Context) (*domain.Role, error) {
	return proxy.CallWithData[*domain.Role](s.proxyService, "CreateRole", p)
}

// DeleteRole via HTTP
// Generated from: @Route "DELETE /{role_id}"
func (s *RoleServiceRemote) DeleteRole(p *request.Context) error {
	return proxy.Call(s.proxyService, "DeleteRole", p)
}

// GetRole via HTTP
// Generated from: @Route "GET /{role_id}"
func (s *RoleServiceRemote) GetRole(p *request.Context) (*domain.Role, error) {
	return proxy.CallWithData[*domain.Role](s.proxyService, "GetRole", p)
}

// ListRoles via HTTP
// Generated from: @Route "GET /"
func (s *RoleServiceRemote) ListRoles(p *request.Context) ([]*domain.Role, error) {
	return proxy.CallWithData[[]*domain.Role](s.proxyService, "ListRoles", p)
}

// UpdateRole via HTTP
// Generated from: @Route "PUT /{role_id}"
func (s *RoleServiceRemote) UpdateRole(p *request.Context) (*domain.Role, error) {
	return proxy.CallWithData[*domain.Role](s.proxyService, "UpdateRole", p)
}


func RoleServiceFactory(deps map[string]any, config map[string]any) any {
	svc := &RoleService{
		RoleStore: deps["role-store"].(repository.RoleStore),
	}
	
	return svc
}

// RoleServiceRemoteFactory creates a remote HTTP client for RoleServiceInterface
// Auto-generated from @RouterService annotation
func RoleServiceRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewRoleServiceRemote(proxyService)
}

// RegisterRoleService registers the role-service with the registry
// Auto-generated from annotations:
//   - @RouterService name="role-service", prefix="${api-auth-prefix:/api/auth}/rbac/tenants/{tenant_id}/apps/{app_id}/roles"
//   - @Inject annotations
//   - @Route annotations on methods
func RegisterRoleService() {
	// Register service type with router configuration
	lokstra_registry.RegisterRouterServiceType("role-service-factory",
		RoleServiceFactory,
		RoleServiceRemoteFactory,
		&deploy.ServiceTypeConfig{
			PathPrefix:  "${api-auth-prefix:/api/auth}/rbac/tenants/{tenant_id}/apps/{app_id}/roles",
			Middlewares: []string{ "recovery", "request_logger", "auth" },
			RouteOverrides: map[string]deploy.RouteConfig{
				"CreateRole": {
					Path: "POST /",
				},
				"DeleteRole": {
					Path: "DELETE /{role_id}",
				},
				"GetRole": {
					Path: "GET /{role_id}",
				},
				"ListRoles": {
					Path: "GET /",
				},
				"UpdateRole": {
					Path: "PUT /{role_id}",
				},
			},
		},
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("role-service",
		"role-service-factory",
		map[string]any{
			"depends-on": []string{ "role-store", },
		})
}


// ============================================================
// FILE: user_permission_service.go
// ============================================================

// UserPermissionServiceRemote implements UserPermissionServiceInterface with HTTP proxy
// Auto-generated from UserPermissionService interface methods
type UserPermissionServiceRemote struct {
	proxyService *proxy.Service
}

// NewUserPermissionServiceRemote creates a new remote user-permission-service proxy
func NewUserPermissionServiceRemote(proxyService *proxy.Service) *UserPermissionServiceRemote {
	return &UserPermissionServiceRemote{
		proxyService: proxyService,
	}
}

// AssignPermissionToUser via HTTP
// Generated from: @Route "POST /"
func (s *UserPermissionServiceRemote) AssignPermissionToUser(p *request.Context) error {
	return proxy.Call(s.proxyService, "AssignPermissionToUser", p)
}

// ListUserPermissions via HTTP
// Generated from: @Route "GET /"
func (s *UserPermissionServiceRemote) ListUserPermissions(p *request.Context) ([]*domain.Permission, error) {
	return proxy.CallWithData[[]*domain.Permission](s.proxyService, "ListUserPermissions", p)
}

// RevokePermissionFromUser via HTTP
// Generated from: @Route "DELETE /{permission_id}"
func (s *UserPermissionServiceRemote) RevokePermissionFromUser(p *request.Context) error {
	return proxy.Call(s.proxyService, "RevokePermissionFromUser", p)
}


func UserPermissionServiceFactory(deps map[string]any, config map[string]any) any {
	svc := &UserPermissionService{
		PermissionStore: deps["permission-store"].(repository.PermissionStore),
		UserPermissionStore: deps["user-permission-store"].(repository.UserPermissionStore),
	}
	
	return svc
}

// UserPermissionServiceRemoteFactory creates a remote HTTP client for UserPermissionServiceInterface
// Auto-generated from @RouterService annotation
func UserPermissionServiceRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewUserPermissionServiceRemote(proxyService)
}

// RegisterUserPermissionService registers the user-permission-service with the registry
// Auto-generated from annotations:
//   - @RouterService name="user-permission-service", prefix="${api-auth-prefix:/api/auth}/rbac/tenants/{tenant_id}/apps/{app_id}/users/{user_id}/permissions"
//   - @Inject annotations
//   - @Route annotations on methods
func RegisterUserPermissionService() {
	// Register service type with router configuration
	lokstra_registry.RegisterRouterServiceType("user-permission-service-factory",
		UserPermissionServiceFactory,
		UserPermissionServiceRemoteFactory,
		&deploy.ServiceTypeConfig{
			PathPrefix:  "${api-auth-prefix:/api/auth}/rbac/tenants/{tenant_id}/apps/{app_id}/users/{user_id}/permissions",
			Middlewares: []string{ "recovery", "request_logger", "auth" },
			RouteOverrides: map[string]deploy.RouteConfig{
				"AssignPermissionToUser": {
					Path: "POST /",
				},
				"ListUserPermissions": {
					Path: "GET /",
				},
				"RevokePermissionFromUser": {
					Path: "DELETE /{permission_id}",
				},
			},
		},
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("user-permission-service",
		"user-permission-service-factory",
		map[string]any{
			"depends-on": []string{ "permission-store", "user-permission-store", },
		})
}


// ============================================================
// FILE: user_role_service.go
// ============================================================

// UserRoleServiceRemote implements UserRoleServiceInterface with HTTP proxy
// Auto-generated from UserRoleService interface methods
type UserRoleServiceRemote struct {
	proxyService *proxy.Service
}

// NewUserRoleServiceRemote creates a new remote user-role-service proxy
func NewUserRoleServiceRemote(proxyService *proxy.Service) *UserRoleServiceRemote {
	return &UserRoleServiceRemote{
		proxyService: proxyService,
	}
}

// AssignRole via HTTP
// Generated from: @Route "POST /"
func (s *UserRoleServiceRemote) AssignRole(p *request.Context) error {
	return proxy.Call(s.proxyService, "AssignRole", p)
}

// ListUserRoles via HTTP
// Generated from: @Route "GET /"
func (s *UserRoleServiceRemote) ListUserRoles(p *request.Context) ([]*domain.Role, error) {
	return proxy.CallWithData[[]*domain.Role](s.proxyService, "ListUserRoles", p)
}

// RevokeRole via HTTP
// Generated from: @Route "DELETE /{role_id}"
func (s *UserRoleServiceRemote) RevokeRole(p *request.Context) error {
	return proxy.Call(s.proxyService, "RevokeRole", p)
}


func UserRoleServiceFactory(deps map[string]any, config map[string]any) any {
	svc := &UserRoleService{
		RoleStore: deps["role-store"].(repository.RoleStore),
		UserRoleStore: deps["user-role-store"].(repository.UserRoleStore),
	}
	
	return svc
}

// UserRoleServiceRemoteFactory creates a remote HTTP client for UserRoleServiceInterface
// Auto-generated from @RouterService annotation
func UserRoleServiceRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewUserRoleServiceRemote(proxyService)
}

// RegisterUserRoleService registers the user-role-service with the registry
// Auto-generated from annotations:
//   - @RouterService name="user-role-service", prefix="${api-auth-prefix:/api/auth}/rbac/tenants/{tenant_id}/apps/{app_id}/users/{user_id}/roles"
//   - @Inject annotations
//   - @Route annotations on methods
func RegisterUserRoleService() {
	// Register service type with router configuration
	lokstra_registry.RegisterRouterServiceType("user-role-service-factory",
		UserRoleServiceFactory,
		UserRoleServiceRemoteFactory,
		&deploy.ServiceTypeConfig{
			PathPrefix:  "${api-auth-prefix:/api/auth}/rbac/tenants/{tenant_id}/apps/{app_id}/users/{user_id}/roles",
			Middlewares: []string{ "recovery", "request_logger", "auth" },
			RouteOverrides: map[string]deploy.RouteConfig{
				"AssignRole": {
					Path: "POST /",
				},
				"ListUserRoles": {
					Path: "GET /",
				},
				"RevokeRole": {
					Path: "DELETE /{role_id}",
				},
			},
		},
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("user-role-service",
		"user-role-service-factory",
		map[string]any{
			"depends-on": []string{ "role-store", "user-role-store", },
		})
}



