// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @EndpointService, @Service, @Inject, @Route
//
// @Inject supports:
//   - "service-name"          : Direct service injection
//   - "@config.key"           : Service name from config value
//   - "cfg:config.key"        : Config value injection
//   - "cfg:@config.key"       : Config value via indirection

package simple

import (
	"github.com/primadi/lokstra/lokstra_registry"
	cast "github.com/primadi/lokstra/common/cast"
)

// Auto-register on package import
func init() {
	RegisterManager()
}

// ============================================================
// FILE: manager.go
// ============================================================

// RegisterManager registers the simple-token-manager with the registry
// Auto-generated from annotations:
//   - @Service name="simple-token-manager"
//   - @Inject annotations
func RegisterManager() {
	lokstra_registry.RegisterLazyService("simple-token-manager", func(deps map[string]any, cfg map[string]any) any {
		svc := &Manager{
			Config: func() *Config {
		if v, ok := cfg["auth.simple_token_manager"]; ok {
			var result *Config
			if err := cast.ToStruct(v, &result, false); err == nil {
				return result
			}
		}
		return nil
	}(),
		}
		
		// Call Init() for post-initialization
		svc.Init()
		
		return svc
	}, map[string]any{
		"auth.simple_token_manager": lokstra_registry.GetConfig[any]("auth.simple_token_manager", nil),
	})
}


