// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @RouterService, @Service, @Inject, @InjectCfgValue, @Route

package authenticator

import (
	"github.com/primadi/lokstra/lokstra_registry"
	core_repository "github.com/primadi/lokstra-auth/infrastructure/repository"
)

// Auto-register on package import
func init() {
	RegisterAPIKeyAuthenticator()
	RegisterBasicAuthenticator()
}

// ============================================================
// FILE: apikey_authenticator.go
// ============================================================

// RegisterAPIKeyAuthenticator registers the apikey-authenticator with the registry
// Auto-generated from annotations:
//   - @Service name="apikey-authenticator"
//   - @Inject annotations
func RegisterAPIKeyAuthenticator() {
	lokstra_registry.RegisterLazyService("apikey-authenticator", func(deps map[string]any, cfg map[string]any) any {
		svc := &APIKeyAuthenticator{
			keyStore: deps["app-key-store"].(core_repository.AppKeyStore),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "app-key-store", },
	})
}


// ============================================================
// FILE: basic_authenticator.go
// ============================================================

// RegisterBasicAuthenticator registers the basic-authenticator with the registry
// Auto-generated from annotations:
//   - @Service name="basic-authenticator"
//   - @Inject annotations
func RegisterBasicAuthenticator() {
	lokstra_registry.RegisterLazyService("basic-authenticator", func(deps map[string]any, cfg map[string]any) any {
		svc := &BasicAuthenticator{
			tenantStore: deps["@store.tenant-store"].(core_repository.TenantStore),
			userStore: deps["@store.user-store"].(core_repository.UserStore),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "@store.tenant-store", "@store.user-store", },
	})
}


