// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @RouterService, @Service, @Inject, @InjectCfgValue, @Route

package validator

import (
	"github.com/primadi/lokstra/lokstra_registry"
)

// Auto-register on package import
func init() {
	RegisterConfigurableValidator()
}

// ============================================================
// FILE: configurable.go
// ============================================================

// RegisterConfigurableValidator registers the credential-validator with the registry
// Auto-generated from annotations:
//   - @Service name="credential-validator"
func RegisterConfigurableValidator() {
	lokstra_registry.RegisterLazyService("credential-validator", func(deps map[string]any, cfg map[string]any) any {
		svc := &ConfigurableValidator{
		}
		
		return svc
	}, map[string]any{
	})
}


