// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @RouterService, @Service, @Inject, @InjectCfgValue, @Route

package application

import (
	"github.com/primadi/lokstra/core/deploy"
	"github.com/primadi/lokstra/core/proxy"
	"github.com/primadi/lokstra/lokstra_registry"
	domain "github.com/primadi/lokstra-auth/credential/domain"
	apikey "github.com/primadi/lokstra-auth/credential/domain/apikey"
	basic "github.com/primadi/lokstra-auth/credential/domain/basic"
	oauth2 "github.com/primadi/lokstra-auth/credential/domain/oauth2"
	passkey "github.com/primadi/lokstra-auth/credential/domain/passkey"
	passwordless "github.com/primadi/lokstra-auth/credential/domain/passwordless"
	validator "github.com/primadi/lokstra-auth/credential/infrastructure/validator"
	core_repository "github.com/primadi/lokstra-auth/infrastructure/repository"
	token "github.com/primadi/lokstra-auth/token"
	request "github.com/primadi/lokstra/core/request"
)

// Auto-register on package import
func init() {
	RegisterAPIKeyAuthService()
	RegisterBasicAuthService()
	RegisterOAuth2AuthService()
	RegisterPasskeyAuthService()
	RegisterPasswordlessAuthService()
}

// ============================================================
// FILE: basic_service.go
// ============================================================

// BasicAuthServiceRemote implements BasicAuthServiceInterface with HTTP proxy
// Auto-generated from BasicAuthService interface methods
type BasicAuthServiceRemote struct {
	proxyService *proxy.Service
}

// NewBasicAuthServiceRemote creates a new remote basic-auth-service proxy
func NewBasicAuthServiceRemote(proxyService *proxy.Service) *BasicAuthServiceRemote {
	return &BasicAuthServiceRemote{
		proxyService: proxyService,
	}
}

// ChangePassword via HTTP
// Generated from: @Route "POST /change-password"
func (s *BasicAuthServiceRemote) ChangePassword(p *request.Context) error {
	return proxy.Call(s.proxyService, "ChangePassword", p)
}

// ForgotPassword via HTTP
// Generated from: @Route "POST /forgot-password"
func (s *BasicAuthServiceRemote) ForgotPassword(p *request.Context) (*basic.ForgotPasswordResponse, error) {
	return proxy.CallWithData[*basic.ForgotPasswordResponse](s.proxyService, "ForgotPassword", p)
}

// Login via HTTP
// Generated from: @Route "POST /login"
func (s *BasicAuthServiceRemote) Login(p *request.Context) (*basic.TokenResponse, error) {
	return proxy.CallWithData[*basic.TokenResponse](s.proxyService, "Login", p)
}

// ResetPassword via HTTP
// Generated from: @Route "POST /reset-password"
func (s *BasicAuthServiceRemote) ResetPassword(p *request.Context) (*basic.ResetPasswordResponse, error) {
	return proxy.CallWithData[*basic.ResetPasswordResponse](s.proxyService, "ResetPassword", p)
}


func BasicAuthServiceFactory(deps map[string]any, config map[string]any) any {
	svc := &BasicAuthService{
		Authenticator: deps["basic-authenticator"].(domain.Authenticator),
		Validator: deps["credential-validator"].(validator.CredentialValidator),
		AppStore: deps["@store.app-store"].(core_repository.AppStore),
		TenantStore: deps["@store.tenant-store"].(core_repository.TenantStore),
		UserStore: deps["@store.user-store"].(core_repository.UserStore),
		TokenManager: deps["token-manager"].(token.TokenManager),
	}
	
	return svc
}

// BasicAuthServiceRemoteFactory creates a remote HTTP client for BasicAuthServiceInterface
// Auto-generated from @RouterService annotation
func BasicAuthServiceRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewBasicAuthServiceRemote(proxyService)
}

// RegisterBasicAuthService registers the basic-auth-service with the registry
// Auto-generated from annotations:
//   - @RouterService name="basic-auth-service", prefix="${api-auth-prefix:/api/auth}/cred/basic"
//   - @Inject annotations
//   - @Route annotations on methods
func RegisterBasicAuthService() {
	// Register service type with router configuration
	lokstra_registry.RegisterRouterServiceType("basic-auth-service-factory",
		BasicAuthServiceFactory,
		BasicAuthServiceRemoteFactory,
		&deploy.ServiceTypeConfig{
			PathPrefix:  "${api-auth-prefix:/api/auth}/cred/basic",
			Middlewares: []string{ "recovery", "request_logger" },
			RouteOverrides: map[string]deploy.RouteConfig{
				"ChangePassword": {
					Path: "POST /change-password",
					Middlewares: []string{ "auth" },
				},
				"ForgotPassword": {
					Path: "POST /forgot-password",
				},
				"Login": {
					Path: "POST /login",
				},
				"ResetPassword": {
					Path: "POST /reset-password",
				},
			},
		},
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("basic-auth-service",
		"basic-auth-service-factory",
		map[string]any{
			"depends-on": []string{ "basic-authenticator", "credential-validator", "@store.app-store", "@store.tenant-store", "@store.user-store", "token-manager", },
		})
}


// ============================================================
// FILE: apikey_service.go
// ============================================================

// APIKeyAuthServiceRemote implements APIKeyAuthServiceInterface with HTTP proxy
// Auto-generated from APIKeyAuthService interface methods
type APIKeyAuthServiceRemote struct {
	proxyService *proxy.Service
}

// NewAPIKeyAuthServiceRemote creates a new remote apikey-auth-service proxy
func NewAPIKeyAuthServiceRemote(proxyService *proxy.Service) *APIKeyAuthServiceRemote {
	return &APIKeyAuthServiceRemote{
		proxyService: proxyService,
	}
}

// Authenticate via HTTP
// Generated from: @Route "POST /authenticate"
func (s *APIKeyAuthServiceRemote) Authenticate(p *request.Context) (*apikey.AuthenticateResponse, error) {
	return proxy.CallWithData[*apikey.AuthenticateResponse](s.proxyService, "Authenticate", p)
}


func APIKeyAuthServiceFactory(deps map[string]any, config map[string]any) any {
	svc := &APIKeyAuthService{
		Authenticator: deps["apikey-authenticator"].(domain.Authenticator),
		Store: deps["@store.app-key-store"].(core_repository.AppKeyStore),
		AppStore: deps["@store.app-store"].(core_repository.AppStore),
		TenantStore: deps["@store.tenant-store"].(core_repository.TenantStore),
	}
	
	return svc
}

// APIKeyAuthServiceRemoteFactory creates a remote HTTP client for APIKeyAuthServiceInterface
// Auto-generated from @RouterService annotation
func APIKeyAuthServiceRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewAPIKeyAuthServiceRemote(proxyService)
}

// RegisterAPIKeyAuthService registers the apikey-auth-service with the registry
// Auto-generated from annotations:
//   - @RouterService name="apikey-auth-service", prefix="${api-auth-prefix:/api/auth}/cred/apikey"
//   - @Inject annotations
//   - @Route annotations on methods
func RegisterAPIKeyAuthService() {
	// Register service type with router configuration
	lokstra_registry.RegisterRouterServiceType("apikey-auth-service-factory",
		APIKeyAuthServiceFactory,
		APIKeyAuthServiceRemoteFactory,
		&deploy.ServiceTypeConfig{
			PathPrefix:  "${api-auth-prefix:/api/auth}/cred/apikey",
			Middlewares: []string{ "recovery", "request_logger" },
			RouteOverrides: map[string]deploy.RouteConfig{
				"Authenticate": {
					Path: "POST /authenticate",
				},
			},
		},
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("apikey-auth-service",
		"apikey-auth-service-factory",
		map[string]any{
			"depends-on": []string{ "apikey-authenticator", "@store.app-key-store", "@store.app-store", "@store.tenant-store", },
		})
}


// ============================================================
// FILE: oauth2_service.go
// ============================================================

// OAuth2AuthServiceRemote implements OAuth2AuthServiceInterface with HTTP proxy
// Auto-generated from OAuth2AuthService interface methods
type OAuth2AuthServiceRemote struct {
	proxyService *proxy.Service
}

// NewOAuth2AuthServiceRemote creates a new remote oauth2-auth-service proxy
func NewOAuth2AuthServiceRemote(proxyService *proxy.Service) *OAuth2AuthServiceRemote {
	return &OAuth2AuthServiceRemote{
		proxyService: proxyService,
	}
}

// Authorize via HTTP
// Generated from: @Route "POST /authorize"
func (s *OAuth2AuthServiceRemote) Authorize(p *request.Context) (*oauth2.AuthorizeResponse, error) {
	return proxy.CallWithData[*oauth2.AuthorizeResponse](s.proxyService, "Authorize", p)
}

// Callback via HTTP
// Generated from: @Route "GET /callback"
func (s *OAuth2AuthServiceRemote) Callback(p *request.Context) (*oauth2.LoginResponse, error) {
	return proxy.CallWithData[*oauth2.LoginResponse](s.proxyService, "Callback", p)
}


func OAuth2AuthServiceFactory(deps map[string]any, config map[string]any) any {
	svc := &OAuth2AuthService{
	}
	
	return svc
}

// OAuth2AuthServiceRemoteFactory creates a remote HTTP client for OAuth2AuthServiceInterface
// Auto-generated from @RouterService annotation
func OAuth2AuthServiceRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewOAuth2AuthServiceRemote(proxyService)
}

// RegisterOAuth2AuthService registers the oauth2-auth-service with the registry
// Auto-generated from annotations:
//   - @RouterService name="oauth2-auth-service", prefix="${api-auth-prefix:/api/auth}/cred/oauth2"
//   - @Route annotations on methods
func RegisterOAuth2AuthService() {
	// Register service type with router configuration
	lokstra_registry.RegisterRouterServiceType("oauth2-auth-service-factory",
		OAuth2AuthServiceFactory,
		OAuth2AuthServiceRemoteFactory,
		&deploy.ServiceTypeConfig{
			PathPrefix:  "${api-auth-prefix:/api/auth}/cred/oauth2",
			Middlewares: []string{ "recovery", "request_logger" },
			RouteOverrides: map[string]deploy.RouteConfig{
				"Authorize": {
					Path: "POST /authorize",
				},
				"Callback": {
					Path: "GET /callback",
				},
			},
		},
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("oauth2-auth-service",
		"oauth2-auth-service-factory",
		map[string]any{
		})
}


// ============================================================
// FILE: passkey_service.go
// ============================================================

// PasskeyAuthServiceRemote implements PasskeyAuthServiceInterface with HTTP proxy
// Auto-generated from PasskeyAuthService interface methods
type PasskeyAuthServiceRemote struct {
	proxyService *proxy.Service
}

// NewPasskeyAuthServiceRemote creates a new remote passkey-auth-service proxy
func NewPasskeyAuthServiceRemote(proxyService *proxy.Service) *PasskeyAuthServiceRemote {
	return &PasskeyAuthServiceRemote{
		proxyService: proxyService,
	}
}

// BeginAuthentication via HTTP
// Generated from: @Route "POST /authenticate/begin"
func (s *PasskeyAuthServiceRemote) BeginAuthentication(p *request.Context) (*passkey.BeginAuthenticationResponse, error) {
	return proxy.CallWithData[*passkey.BeginAuthenticationResponse](s.proxyService, "BeginAuthentication", p)
}

// BeginRegistration via HTTP
// Generated from: @Route "POST /register/begin"
func (s *PasskeyAuthServiceRemote) BeginRegistration(p *request.Context) (*passkey.BeginRegistrationResponse, error) {
	return proxy.CallWithData[*passkey.BeginRegistrationResponse](s.proxyService, "BeginRegistration", p)
}

// DeleteCredential via HTTP
// Generated from: @Route "DELETE /credentials/{credential_id}"
func (s *PasskeyAuthServiceRemote) DeleteCredential(p *request.Context) error {
	return proxy.Call(s.proxyService, "DeleteCredential", p)
}

// FinishAuthentication via HTTP
// Generated from: @Route "POST /authenticate/finish"
func (s *PasskeyAuthServiceRemote) FinishAuthentication(p *request.Context) (*passkey.FinishAuthenticationResponse, error) {
	return proxy.CallWithData[*passkey.FinishAuthenticationResponse](s.proxyService, "FinishAuthentication", p)
}

// FinishRegistration via HTTP
// Generated from: @Route "POST /register/finish"
func (s *PasskeyAuthServiceRemote) FinishRegistration(p *request.Context) (*passkey.FinishRegistrationResponse, error) {
	return proxy.CallWithData[*passkey.FinishRegistrationResponse](s.proxyService, "FinishRegistration", p)
}

// ListCredentials via HTTP
// Generated from: @Route "GET /credentials/{user_id}"
func (s *PasskeyAuthServiceRemote) ListCredentials(p *request.Context) ([]passkey.PasskeyCredential, error) {
	return proxy.CallWithData[[]passkey.PasskeyCredential](s.proxyService, "ListCredentials", p)
}


func PasskeyAuthServiceFactory(deps map[string]any, config map[string]any) any {
	svc := &PasskeyAuthService{
	}
	
	return svc
}

// PasskeyAuthServiceRemoteFactory creates a remote HTTP client for PasskeyAuthServiceInterface
// Auto-generated from @RouterService annotation
func PasskeyAuthServiceRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewPasskeyAuthServiceRemote(proxyService)
}

// RegisterPasskeyAuthService registers the passkey-auth-service with the registry
// Auto-generated from annotations:
//   - @RouterService name="passkey-auth-service", prefix="${api-auth-prefix:/api/auth}/cred/passkey"
//   - @Route annotations on methods
func RegisterPasskeyAuthService() {
	// Register service type with router configuration
	lokstra_registry.RegisterRouterServiceType("passkey-auth-service-factory",
		PasskeyAuthServiceFactory,
		PasskeyAuthServiceRemoteFactory,
		&deploy.ServiceTypeConfig{
			PathPrefix:  "${api-auth-prefix:/api/auth}/cred/passkey",
			Middlewares: []string{ "recovery", "request_logger" },
			RouteOverrides: map[string]deploy.RouteConfig{
				"BeginAuthentication": {
					Path: "POST /authenticate/begin",
				},
				"BeginRegistration": {
					Path: "POST /register/begin",
				},
				"DeleteCredential": {
					Path: "DELETE /credentials/{credential_id}",
				},
				"FinishAuthentication": {
					Path: "POST /authenticate/finish",
				},
				"FinishRegistration": {
					Path: "POST /register/finish",
				},
				"ListCredentials": {
					Path: "GET /credentials/{user_id}",
				},
			},
		},
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("passkey-auth-service",
		"passkey-auth-service-factory",
		map[string]any{
		})
}


// ============================================================
// FILE: passwordless_service.go
// ============================================================

// PasswordlessAuthServiceRemote implements PasswordlessAuthServiceInterface with HTTP proxy
// Auto-generated from PasswordlessAuthService interface methods
type PasswordlessAuthServiceRemote struct {
	proxyService *proxy.Service
}

// NewPasswordlessAuthServiceRemote creates a new remote passwordless-auth-service proxy
func NewPasswordlessAuthServiceRemote(proxyService *proxy.Service) *PasswordlessAuthServiceRemote {
	return &PasswordlessAuthServiceRemote{
		proxyService: proxyService,
	}
}

// ResendCode via HTTP
// Generated from: @Route "POST /resend-code"
func (s *PasswordlessAuthServiceRemote) ResendCode(p *request.Context) (*passwordless.SendCodeResponse, error) {
	return proxy.CallWithData[*passwordless.SendCodeResponse](s.proxyService, "ResendCode", p)
}

// SendCode via HTTP
// Generated from: @Route "POST /send-code"
func (s *PasswordlessAuthServiceRemote) SendCode(p *request.Context) (*passwordless.SendCodeResponse, error) {
	return proxy.CallWithData[*passwordless.SendCodeResponse](s.proxyService, "SendCode", p)
}

// SendMagicLink via HTTP
// Generated from: @Route "POST /send-magic-link"
func (s *PasswordlessAuthServiceRemote) SendMagicLink(p *request.Context) (*passwordless.SendMagicLinkResponse, error) {
	return proxy.CallWithData[*passwordless.SendMagicLinkResponse](s.proxyService, "SendMagicLink", p)
}

// VerifyCode via HTTP
// Generated from: @Route "POST /verify-code"
func (s *PasswordlessAuthServiceRemote) VerifyCode(p *request.Context) (*passwordless.VerifyCodeResponse, error) {
	return proxy.CallWithData[*passwordless.VerifyCodeResponse](s.proxyService, "VerifyCode", p)
}

// VerifyMagicLink via HTTP
// Generated from: @Route "GET /verify-magic-link/{token}"
func (s *PasswordlessAuthServiceRemote) VerifyMagicLink(p *request.Context) (*passwordless.VerifyMagicLinkResponse, error) {
	return proxy.CallWithData[*passwordless.VerifyMagicLinkResponse](s.proxyService, "VerifyMagicLink", p)
}


func PasswordlessAuthServiceFactory(deps map[string]any, config map[string]any) any {
	svc := &PasswordlessAuthService{
	}
	
	return svc
}

// PasswordlessAuthServiceRemoteFactory creates a remote HTTP client for PasswordlessAuthServiceInterface
// Auto-generated from @RouterService annotation
func PasswordlessAuthServiceRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewPasswordlessAuthServiceRemote(proxyService)
}

// RegisterPasswordlessAuthService registers the passwordless-auth-service with the registry
// Auto-generated from annotations:
//   - @RouterService name="passwordless-auth-service", prefix="${api-auth-prefix:/api/auth}/cred/passwordless"
//   - @Route annotations on methods
func RegisterPasswordlessAuthService() {
	// Register service type with router configuration
	lokstra_registry.RegisterRouterServiceType("passwordless-auth-service-factory",
		PasswordlessAuthServiceFactory,
		PasswordlessAuthServiceRemoteFactory,
		&deploy.ServiceTypeConfig{
			PathPrefix:  "${api-auth-prefix:/api/auth}/cred/passwordless",
			Middlewares: []string{ "recovery", "request_logger" },
			RouteOverrides: map[string]deploy.RouteConfig{
				"ResendCode": {
					Path: "POST /resend-code",
				},
				"SendCode": {
					Path: "POST /send-code",
				},
				"SendMagicLink": {
					Path: "POST /send-magic-link",
				},
				"VerifyCode": {
					Path: "POST /verify-code",
				},
				"VerifyMagicLink": {
					Path: "GET /verify-magic-link/{token}",
				},
			},
		},
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("passwordless-auth-service",
		"passwordless-auth-service-factory",
		map[string]any{
		})
}



