// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @RouterService, @Service, @Inject, @InjectCfgValue, @Route

package application

import (
	"github.com/primadi/lokstra/core/deploy"
	"github.com/primadi/lokstra/core/proxy"
	"github.com/primadi/lokstra/lokstra_registry"
	domain "github.com/primadi/lokstra-auth/authz/domain"
	repository "github.com/primadi/lokstra-auth/infrastructure/repository"
	request "github.com/primadi/lokstra/core/request"
)

// Auto-register on package import
func init() {
	RegisterPolicyService()
}

// ============================================================
// FILE: policy_service.go
// ============================================================

// PolicyServiceRemote implements PolicyServiceInterface with HTTP proxy
// Auto-generated from PolicyService interface methods
type PolicyServiceRemote struct {
	proxyService *proxy.Service
}

// NewPolicyServiceRemote creates a new remote policy-service proxy
func NewPolicyServiceRemote(proxyService *proxy.Service) *PolicyServiceRemote {
	return &PolicyServiceRemote{
		proxyService: proxyService,
	}
}

// CreatePolicy via HTTP
// Generated from: @Route "POST /"
func (s *PolicyServiceRemote) CreatePolicy(p *request.Context) (*domain.Policy, error) {
	return proxy.CallWithData[*domain.Policy](s.proxyService, "CreatePolicy", p)
}

// DeletePolicy via HTTP
// Generated from: @Route "DELETE /{policy_id}"
func (s *PolicyServiceRemote) DeletePolicy(p *request.Context) error {
	return proxy.Call(s.proxyService, "DeletePolicy", p)
}

// FindPoliciesByResource via HTTP
// Generated from: @Route "GET /by-resource/{resource_type}"
func (s *PolicyServiceRemote) FindPoliciesByResource(p *request.Context) ([]*domain.Policy, error) {
	return proxy.CallWithData[[]*domain.Policy](s.proxyService, "FindPoliciesByResource", p)
}

// FindPoliciesBySubject via HTTP
// Generated from: @Route "GET /by-subject/{subject_id}"
func (s *PolicyServiceRemote) FindPoliciesBySubject(p *request.Context) ([]*domain.Policy, error) {
	return proxy.CallWithData[[]*domain.Policy](s.proxyService, "FindPoliciesBySubject", p)
}

// GetPolicy via HTTP
// Generated from: @Route "GET /{policy_id}"
func (s *PolicyServiceRemote) GetPolicy(p *request.Context) (*domain.Policy, error) {
	return proxy.CallWithData[*domain.Policy](s.proxyService, "GetPolicy", p)
}

// ListPolicies via HTTP
// Generated from: @Route "GET /"
func (s *PolicyServiceRemote) ListPolicies(p *request.Context) ([]*domain.Policy, error) {
	return proxy.CallWithData[[]*domain.Policy](s.proxyService, "ListPolicies", p)
}

// UpdatePolicy via HTTP
// Generated from: @Route "PUT /{policy_id}"
func (s *PolicyServiceRemote) UpdatePolicy(p *request.Context) (*domain.Policy, error) {
	return proxy.CallWithData[*domain.Policy](s.proxyService, "UpdatePolicy", p)
}


func PolicyServiceFactory(deps map[string]any, config map[string]any) any {
	svc := &PolicyService{
		PolicyStore: deps["@store.policy-store"].(repository.PolicyStore),
	}
	
	return svc
}

// PolicyServiceRemoteFactory creates a remote HTTP client for PolicyServiceInterface
// Auto-generated from @RouterService annotation
func PolicyServiceRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewPolicyServiceRemote(proxyService)
}

// RegisterPolicyService registers the policy-service with the registry
// Auto-generated from annotations:
//   - @RouterService name="policy-service", prefix="${api-auth-prefix:/api/auth}/authz/tenants/{tenant_id}/apps/{app_id}/policies"
//   - @Inject annotations
//   - @Route annotations on methods
func RegisterPolicyService() {
	// Register service type with router configuration
	lokstra_registry.RegisterRouterServiceType("policy-service-factory",
		PolicyServiceFactory,
		PolicyServiceRemoteFactory,
		&deploy.ServiceTypeConfig{
			PathPrefix:  "${api-auth-prefix:/api/auth}/authz/tenants/{tenant_id}/apps/{app_id}/policies",
			Middlewares: []string{ "recovery", "request_logger", "auth" },
			RouteOverrides: map[string]deploy.RouteConfig{
				"CreatePolicy": {
					Path: "POST /",
				},
				"DeletePolicy": {
					Path: "DELETE /{policy_id}",
				},
				"FindPoliciesByResource": {
					Path: "GET /by-resource/{resource_type}",
				},
				"FindPoliciesBySubject": {
					Path: "GET /by-subject/{subject_id}",
				},
				"GetPolicy": {
					Path: "GET /{policy_id}",
				},
				"ListPolicies": {
					Path: "GET /",
				},
				"UpdatePolicy": {
					Path: "PUT /{policy_id}",
				},
			},
		},
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("policy-service",
		"policy-service-factory",
		map[string]any{
			"depends-on": []string{ "@store.policy-store", },
		})
}


