// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @EndpointService, @Service, @Inject, @Route
//
// @Inject supports:
//   - "service-name"          : Direct service injection
//   - "@config.key"           : Service name from config value
//   - "cfg:config.key"        : Config value injection
//   - "cfg:@config.key"       : Config value via indirection

package application

import (
	"github.com/primadi/lokstra/core/deploy"
	"github.com/primadi/lokstra/core/proxy"
	"github.com/primadi/lokstra/lokstra_registry"
	request "github.com/primadi/lokstra/core/request"
	domaincore "github.com/primadi/lokstra-auth/pkg/domain/core"
	serviceapi "github.com/primadi/lokstra/serviceapi"
	token "github.com/primadi/lokstra-auth/pkg/service/token"
	store "github.com/primadi/lokstra-auth/pkg/store"
)

// Auto-register on package import
func init() {
	RegisterTenantService()
}

// ============================================================
// FILE: tenant_service.go
// ============================================================

// TenantServiceRemote implements TenantServiceInterface with HTTP proxy
// Auto-generated from TenantService interface methods
type TenantServiceRemote struct {
	proxyService *proxy.Service
}

// NewTenantServiceRemote creates a new remote tenant-service proxy
func NewTenantServiceRemote(proxyService *proxy.Service) *TenantServiceRemote {
	return &TenantServiceRemote{
		proxyService: proxyService,
	}
}

// ActivateTenant via HTTP
// Generated from: @Route "POST /{id}/activate"
func (s *TenantServiceRemote) ActivateTenant(p *request.Context) (*domaincore.Tenant, error) {
	return proxy.CallWithData[*domaincore.Tenant](s.proxyService, "ActivateTenant", p)
}

// CreateTenant via HTTP
// Generated from: @Route "POST /"
func (s *TenantServiceRemote) CreateTenant(p *request.Context) (*domaincore.Tenant, error) {
	return proxy.CallWithData[*domaincore.Tenant](s.proxyService, "CreateTenant", p)
}

// DeleteTenant via HTTP
// Generated from: @Route "DELETE /{id}"
func (s *TenantServiceRemote) DeleteTenant(p *request.Context) error {
	return proxy.Call(s.proxyService, "DeleteTenant", p)
}

// GetTenant via HTTP
// Generated from: @Route "GET /{id}"
func (s *TenantServiceRemote) GetTenant(p *request.Context) (*domaincore.Tenant, error) {
	return proxy.CallWithData[*domaincore.Tenant](s.proxyService, "GetTenant", p)
}

// ListTenants via HTTP
// Generated from: @Route "GET /"
func (s *TenantServiceRemote) ListTenants(p *request.Context) ([]*domaincore.Tenant, error) {
	return proxy.CallWithData[[]*domaincore.Tenant](s.proxyService, "ListTenants", p)
}

// SuspendTenant via HTTP
// Generated from: @Route "POST /{id}/suspend"
func (s *TenantServiceRemote) SuspendTenant(p *request.Context) (*domaincore.Tenant, error) {
	return proxy.CallWithData[*domaincore.Tenant](s.proxyService, "SuspendTenant", p)
}

// UpdateTenant via HTTP
// Generated from: @Route "PUT /{id}"
func (s *TenantServiceRemote) UpdateTenant(p *request.Context) (*domaincore.Tenant, error) {
	return proxy.CallWithData[*domaincore.Tenant](s.proxyService, "UpdateTenant", p)
}


func TenantServiceFactory(deps map[string]any, config map[string]any) any {
	svc := &TenantService{
		AppStore: deps["@auth.app-store"].(store.AppStore),
		EventBus: deps["@auth.event-bus"].(serviceapi.EventBus),
		TenantStore: deps["@auth.tenant-store"].(store.TenantStore),
		TokenManager: deps["@auth.token-manager"].(token.TokenManager),
		UserAppStore: deps["@auth.user-app-store"].(store.UserAppStore),
		UserStore: deps["@auth.user-store"].(store.UserStore),
		EmailService: deps["@email-service"].(serviceapi.EmailSender),
	}
	
	return svc
}

// TenantServiceRemoteFactory creates a remote HTTP client for TenantServiceInterface
// Auto-generated from @EndpointService annotation
func TenantServiceRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewTenantServiceRemote(proxyService)
}

// RegisterTenantService registers the tenant-service with the registry
// Auto-generated from annotations:
//   - @EndpointService name="tenant-service", prefix="${auth.path-prefix:/auth}/tenants"
//   - @Inject annotations
//   - @Route annotations on methods
func RegisterTenantService() {
	// Register service type with router configuration
	lokstra_registry.RegisterRouterServiceType("tenant-service-factory",
		TenantServiceFactory,
		TenantServiceRemoteFactory,
		&deploy.ServiceTypeConfig{
			PathPrefix:  "${auth.path-prefix:/auth}/tenants",
			Middlewares: []string{ "recovery", "request_logger" },
			RouteOverrides: map[string]deploy.RouteConfig{
				"ActivateTenant": {
					Path: "POST /{id}/activate",
				},
				"CreateTenant": {
					Path: "POST /",
				},
				"DeleteTenant": {
					Path: "DELETE /{id}",
				},
				"GetTenant": {
					Path: "GET /{id}",
				},
				"ListTenants": {
					Path: "GET /",
				},
				"SuspendTenant": {
					Path: "POST /{id}/suspend",
				},
				"UpdateTenant": {
					Path: "PUT /{id}",
				},
			},
		},
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("tenant-service",
		"tenant-service-factory",
		map[string]any{
			"depends-on": []string{ "@auth.app-store", "@auth.event-bus", "@auth.tenant-store", "@auth.token-manager", "@auth.user-app-store", "@auth.user-store", "@email-service", },
		})
}


