// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @EndpointService, @Service, @Inject, @Route
//
// @Inject supports:
//   - "service-name"          : Direct service injection
//   - "@config.key"           : Service name from config value
//   - "cfg:config.key"        : Config value injection
//   - "cfg:@config.key"       : Config value via indirection

package tenant

import (
	"github.com/primadi/lokstra/core/deploy"
	"github.com/primadi/lokstra/core/proxy"
	"github.com/primadi/lokstra/lokstra_registry"
	domaincore "github.com/primadi/lokstra-auth/pkg/domain/core"
	store "github.com/primadi/lokstra-auth/pkg/store"
	validator "github.com/primadi/lokstra-auth/pkg/utils/validator"
	request "github.com/primadi/lokstra/core/request"
)

// Auto-register on package import
func init() {
	RegisterUserService()
}

// ============================================================
// FILE: user_service.go
// ============================================================

// UserServiceRemote implements UserServiceInterface with HTTP proxy
// Auto-generated from UserService interface methods
type UserServiceRemote struct {
	proxyService *proxy.Service
}

// NewUserServiceRemote creates a new remote user-service proxy
func NewUserServiceRemote(proxyService *proxy.Service) *UserServiceRemote {
	return &UserServiceRemote{
		proxyService: proxyService,
	}
}

// ActivateUser via HTTP
// Generated from: @Route "POST /id/{id}/activate"
func (s *UserServiceRemote) ActivateUser(p *request.Context) error {
	return proxy.Call(s.proxyService, "ActivateUser", p)
}

// AssignUserToApp via HTTP
// Generated from: @Route "POST /id/{user_id}/assign-app"
func (s *UserServiceRemote) AssignUserToApp(p *request.Context) error {
	return proxy.Call(s.proxyService, "AssignUserToApp", p)
}

// CreateUser via HTTP
// Generated from: @Route "POST /"
func (s *UserServiceRemote) CreateUser(p *request.Context) (*domaincore.User, error) {
	return proxy.CallWithData[*domaincore.User](s.proxyService, "CreateUser", p)
}

// DeleteUser via HTTP
// Generated from: @Route "DELETE /id/{id}"
func (s *UserServiceRemote) DeleteUser(p *request.Context) error {
	return proxy.Call(s.proxyService, "DeleteUser", p)
}

// GetUser via HTTP
// Generated from: @Route "GET /id/{id}"
func (s *UserServiceRemote) GetUser(p *request.Context) (*domaincore.User, error) {
	return proxy.CallWithData[*domaincore.User](s.proxyService, "GetUser", p)
}

// GetUserByEmail via HTTP
// Generated from: @Route "GET /by-email/{email}"
func (s *UserServiceRemote) GetUserByEmail(p *request.Context) (*domaincore.User, error) {
	return proxy.CallWithData[*domaincore.User](s.proxyService, "GetUserByEmail", p)
}

// GetUserByUsername via HTTP
// Generated from: @Route "GET /by-username/{username}"
func (s *UserServiceRemote) GetUserByUsername(p *request.Context) (*domaincore.User, error) {
	return proxy.CallWithData[*domaincore.User](s.proxyService, "GetUserByUsername", p)
}

// ListUserApps via HTTP
// Generated from: @Route "GET /id/{id}/apps"
func (s *UserServiceRemote) ListUserApps(p *request.Context) ([]string, error) {
	return proxy.CallWithData[[]string](s.proxyService, "ListUserApps", p)
}

// ListUsers via HTTP
// Generated from: @Route "GET /"
func (s *UserServiceRemote) ListUsers(p *request.Context) ([]*domaincore.User, error) {
	return proxy.CallWithData[[]*domaincore.User](s.proxyService, "ListUsers", p)
}

// RemovePassword via HTTP
// Generated from: @Route "DELETE /id/{id}/password"
func (s *UserServiceRemote) RemovePassword(p *request.Context) error {
	return proxy.Call(s.proxyService, "RemovePassword", p)
}

// RemoveUserFromApp via HTTP
// Generated from: @Route "DELETE /id/{user_id}/remove-app"
func (s *UserServiceRemote) RemoveUserFromApp(p *request.Context) error {
	return proxy.Call(s.proxyService, "RemoveUserFromApp", p)
}

// SetPassword via HTTP
// Generated from: @Route "POST /id/{id}/password"
func (s *UserServiceRemote) SetPassword(p *request.Context) error {
	return proxy.Call(s.proxyService, "SetPassword", p)
}

// SuspendUser via HTTP
// Generated from: @Route "POST /id/{id}/suspend"
func (s *UserServiceRemote) SuspendUser(p *request.Context) error {
	return proxy.Call(s.proxyService, "SuspendUser", p)
}

// UpdateUser via HTTP
// Generated from: @Route "PUT /id/{id}"
func (s *UserServiceRemote) UpdateUser(p *request.Context) error {
	return proxy.Call(s.proxyService, "UpdateUser", p)
}


func UserServiceFactory(deps map[string]any, config map[string]any) any {
	svc := &UserService{
		AppStore: deps["@auth.app-store"].(store.AppStore),
		TenantStore: deps["@auth.tenant-store"].(store.TenantStore),
		UserAppStore: deps["@auth.user-app-store"].(store.UserAppStore),
		UserStore: deps["@auth.user-store"].(store.UserStore),
		Validator: deps["credential-validator"].(validator.CredentialValidator),
	}
	
	return svc
}

// UserServiceRemoteFactory creates a remote HTTP client for UserServiceInterface
// Auto-generated from @EndpointService annotation
func UserServiceRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewUserServiceRemote(proxyService)
}

// RegisterUserService registers the user-service with the registry
// Auto-generated from annotations:
//   - @EndpointService name="user-service", prefix="${api-auth-prefix:/auth}/users"
//   - @Inject annotations
//   - @Route annotations on methods
func RegisterUserService() {
	// Register service type with router configuration
	lokstra_registry.RegisterRouterServiceType("user-service-factory",
		UserServiceFactory,
		UserServiceRemoteFactory,
		&deploy.ServiceTypeConfig{
			PathPrefix:  "${api-auth-prefix:/auth}/users",
			Middlewares: []string{ "recovery", "request_logger" },
			RouteOverrides: map[string]deploy.RouteConfig{
				"ActivateUser": {
					Path: "POST /id/{id}/activate",
				},
				"AssignUserToApp": {
					Path: "POST /id/{user_id}/assign-app",
				},
				"CreateUser": {
					Path: "POST /",
				},
				"DeleteUser": {
					Path: "DELETE /id/{id}",
				},
				"GetUser": {
					Path: "GET /id/{id}",
				},
				"GetUserByEmail": {
					Path: "GET /by-email/{email}",
				},
				"GetUserByUsername": {
					Path: "GET /by-username/{username}",
				},
				"ListUserApps": {
					Path: "GET /id/{id}/apps",
				},
				"ListUsers": {
					Path: "GET /",
				},
				"RemovePassword": {
					Path: "DELETE /id/{id}/password",
				},
				"RemoveUserFromApp": {
					Path: "DELETE /id/{user_id}/remove-app",
				},
				"SetPassword": {
					Path: "POST /id/{id}/password",
				},
				"SuspendUser": {
					Path: "POST /id/{id}/suspend",
				},
				"UpdateUser": {
					Path: "PUT /id/{id}",
				},
			},
		},
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("user-service",
		"user-service-factory",
		map[string]any{
			"depends-on": []string{ "@auth.app-store", "@auth.tenant-store", "@auth.user-app-store", "@auth.user-store", "credential-validator", },
		})
}


