// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation to auto-register services via init()
// This file imports all packages containing @Service or @RouterService annotations

package main

import (
	_ "github.com/primadi/lokstra-auth/authz/application"
	_ "github.com/primadi/lokstra-auth/core/application"
	_ "github.com/primadi/lokstra-auth/credential/application"
	_ "github.com/primadi/lokstra-auth/credential/infrastructure/authenticator"
	_ "github.com/primadi/lokstra-auth/credential/infrastructure/validator"
	_ "github.com/primadi/lokstra-auth/examples/01_deployment/services"
	_ "github.com/primadi/lokstra-auth/examples/01_deployment/services"
	_ "github.com/primadi/lokstra-auth/infrastructure/repository/memory"
	_ "github.com/primadi/lokstra-auth/infrastructure/repository/postgres"
	_ "github.com/primadi/lokstra-auth/rbac/application"
	_ "github.com/primadi/lokstra-auth/token/application"
)
