// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @RouterService, @Service, @Inject, @InjectCfgValue, @Route

package postgres

import (
	"github.com/primadi/lokstra/lokstra_registry"
	serviceapi "github.com/primadi/lokstra/serviceapi"
)

// Auto-register on package import
func init() {
	RegisterAuditLogStore()
	RegisterPermissionCompositionStore()
	RegisterPostgresAppKeyStore()
	RegisterPostgresAppStore()
	RegisterPostgresBranchStore()
	RegisterPostgresCredentialProviderStore()
	RegisterPostgresPermissionStore()
	RegisterPostgresPolicyStore()
	RegisterPostgresRoleStore()
	RegisterPostgresTenantStore()
	RegisterPostgresUserAppStore()
	RegisterPostgresUserIdentityStore()
	RegisterPostgresUserRoleStore()
	RegisterPostgresUserStore()
}

// ============================================================
// FILE: app_key_store.go
// ============================================================

// RegisterPostgresAppKeyStore registers the postgres-app-key-store with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-app-key-store"
//   - @Inject annotations
func RegisterPostgresAppKeyStore() {
	lokstra_registry.RegisterLazyService("postgres-app-key-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &PostgresAppKeyStore{
			dbPool: deps["db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_auth", },
	})
}


// ============================================================
// FILE: app_store.go
// ============================================================

// RegisterPostgresAppStore registers the postgres-app-store with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-app-store"
//   - @Inject annotations
func RegisterPostgresAppStore() {
	lokstra_registry.RegisterLazyService("postgres-app-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &PostgresAppStore{
			dbPool: deps["db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_auth", },
	})
}


// ============================================================
// FILE: audit_log_store.go
// ============================================================

// RegisterAuditLogStore registers the postgres-audit-log-store with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-audit-log-store"
//   - @Inject annotations
func RegisterAuditLogStore() {
	lokstra_registry.RegisterLazyService("postgres-audit-log-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &AuditLogStore{
			dbPool: deps["db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_auth", },
	})
}


// ============================================================
// FILE: branch_store.go
// ============================================================

// RegisterPostgresBranchStore registers the postgres-branch-store with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-branch-store"
//   - @Inject annotations
func RegisterPostgresBranchStore() {
	lokstra_registry.RegisterLazyService("postgres-branch-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &PostgresBranchStore{
			dbPool: deps["db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_auth", },
	})
}


// ============================================================
// FILE: credential_provider_store.go
// ============================================================

// RegisterPostgresCredentialProviderStore registers the postgres-credential-provider-store with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-credential-provider-store"
//   - @Inject annotations
func RegisterPostgresCredentialProviderStore() {
	lokstra_registry.RegisterLazyService("postgres-credential-provider-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &PostgresCredentialProviderStore{
			dbPool: deps["db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_auth", },
	})
}


// ============================================================
// FILE: permission_composition_store.go
// ============================================================

// RegisterPermissionCompositionStore registers the postgres-permission-composition-store with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-permission-composition-store"
//   - @Inject annotations
func RegisterPermissionCompositionStore() {
	lokstra_registry.RegisterLazyService("postgres-permission-composition-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &PermissionCompositionStore{
			dbPool: deps["db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_auth", },
	})
}


// ============================================================
// FILE: permission_store.go
// ============================================================

// RegisterPostgresPermissionStore registers the postgres-permission-store with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-permission-store"
//   - @Inject annotations
func RegisterPostgresPermissionStore() {
	lokstra_registry.RegisterLazyService("postgres-permission-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &PostgresPermissionStore{
			dbPool: deps["db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_auth", },
	})
}


// ============================================================
// FILE: policy_store.go
// ============================================================

// RegisterPostgresPolicyStore registers the postgres-policy-store with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-policy-store"
//   - @Inject annotations
func RegisterPostgresPolicyStore() {
	lokstra_registry.RegisterLazyService("postgres-policy-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &PostgresPolicyStore{
			dbPool: deps["db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_auth", },
	})
}


// ============================================================
// FILE: role_store.go
// ============================================================

// RegisterPostgresRoleStore registers the postgres-role-store with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-role-store"
//   - @Inject annotations
func RegisterPostgresRoleStore() {
	lokstra_registry.RegisterLazyService("postgres-role-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &PostgresRoleStore{
			dbPool: deps["db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_auth", },
	})
}


// ============================================================
// FILE: tenant_store.go
// ============================================================

// RegisterPostgresTenantStore registers the postgres-tenant-store with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-tenant-store"
//   - @Inject annotations
func RegisterPostgresTenantStore() {
	lokstra_registry.RegisterLazyService("postgres-tenant-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &PostgresTenantStore{
			dbPool: deps["db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_auth", },
	})
}


// ============================================================
// FILE: user_app_store.go
// ============================================================

// RegisterPostgresUserAppStore registers the postgres-user-app-store with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-user-app-store"
//   - @Inject annotations
func RegisterPostgresUserAppStore() {
	lokstra_registry.RegisterLazyService("postgres-user-app-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &PostgresUserAppStore{
			dbPool: deps["db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_auth", },
	})
}


// ============================================================
// FILE: user_identity_store.go
// ============================================================

// RegisterPostgresUserIdentityStore registers the postgres-user-identity-store with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-user-identity-store"
//   - @Inject annotations
func RegisterPostgresUserIdentityStore() {
	lokstra_registry.RegisterLazyService("postgres-user-identity-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &PostgresUserIdentityStore{
			dbPool: deps["db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_auth", },
	})
}


// ============================================================
// FILE: user_role_store.go
// ============================================================

// RegisterPostgresUserRoleStore registers the postgres-user-role-store with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-user-role-store"
//   - @Inject annotations
func RegisterPostgresUserRoleStore() {
	lokstra_registry.RegisterLazyService("postgres-user-role-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &PostgresUserRoleStore{
			dbPool: deps["db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_auth", },
	})
}


// ============================================================
// FILE: user_store.go
// ============================================================

// RegisterPostgresUserStore registers the postgres-user-store with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-user-store"
//   - @Inject annotations
func RegisterPostgresUserStore() {
	lokstra_registry.RegisterLazyService("postgres-user-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &PostgresUserStore{
			dbPool: deps["db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_auth", },
	})
}


