// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation to auto-register services via init()
// This file imports all packages containing @Service or @EndpointService annotations

package main

import (
	_ "github.com/primadi/lokstra-auth/pkg/endpoint/global"
	_ "github.com/primadi/lokstra-auth/pkg/endpoint/tenant"
	_ "github.com/primadi/lokstra-auth/pkg/service/authenticator"
	_ "github.com/primadi/lokstra-auth/pkg/service/token/jwt"
	_ "github.com/primadi/lokstra-auth/pkg/service/token/simple"
	_ "github.com/primadi/lokstra-auth/pkg/store/postgres"
	_ "github.com/primadi/lokstra-auth/pkg/utils/validator"
)
