// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @EndpointService, @Service, @Inject, @Route
//
// @Inject supports:
//   - "service-name"          : Direct service injection
//   - "@config.key"           : Service name from config value
//   - "cfg:config.key"        : Config value injection
//   - "cfg:@config.key"       : Config value via indirection

package postgres

import (
	"github.com/primadi/lokstra/lokstra_registry"
	serviceapi "github.com/primadi/lokstra/serviceapi"
)

// Auto-register on package import
func init() {
	RegisterpgAppKeyStore()
	RegisterpgAppStore()
	RegisterpgBranchStore()
	RegisterpgCredentialProviderStore()
	RegisterpgPermissionCompositionStore()
	RegisterpgPermissionStore()
	RegisterpgPolicyStore()
	RegisterpgRefreshTokenStore()
	RegisterpgRolePermissionStore()
	RegisterpgRoleStore()
	RegisterpgSessionStore()
	RegisterpgTenantStore()
	RegisterpgUserAppStore()
	RegisterpgUserIdentityStore()
	RegisterpgUserPermissionStore()
	RegisterpgUserRoleStore()
	RegisterpgUserStore()
}

// ============================================================
// FILE: app_key_store.go
// ============================================================

// RegisterpgAppKeyStore registers the pg-app-key-store with the registry
// Auto-generated from annotations:
//   - @Service name="pg-app-key-store"
//   - @Inject annotations
func RegisterpgAppKeyStore() {
	lokstra_registry.RegisterLazyService("pg-app-key-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &pgAppKeyStore{
			dbPool: deps["@auth.db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "@auth.db_auth", },
	})
}


// ============================================================
// FILE: app_store.go
// ============================================================

// RegisterpgAppStore registers the pg-app-store with the registry
// Auto-generated from annotations:
//   - @Service name="pg-app-store"
//   - @Inject annotations
func RegisterpgAppStore() {
	lokstra_registry.RegisterLazyService("pg-app-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &pgAppStore{
			dbPool: deps["@auth.db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "@auth.db_auth", },
	})
}


// ============================================================
// FILE: branch_store.go
// ============================================================

// RegisterpgBranchStore registers the pg-branch-store with the registry
// Auto-generated from annotations:
//   - @Service name="pg-branch-store"
//   - @Inject annotations
func RegisterpgBranchStore() {
	lokstra_registry.RegisterLazyService("pg-branch-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &pgBranchStore{
			dbPool: deps["@auth.db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "@auth.db_auth", },
	})
}


// ============================================================
// FILE: credential_provider_store.go
// ============================================================

// RegisterpgCredentialProviderStore registers the pg-credential-provider-store with the registry
// Auto-generated from annotations:
//   - @Service name="pg-credential-provider-store"
//   - @Inject annotations
func RegisterpgCredentialProviderStore() {
	lokstra_registry.RegisterLazyService("pg-credential-provider-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &pgCredentialProviderStore{
			dbPool: deps["@auth.db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "@auth.db_auth", },
	})
}


// ============================================================
// FILE: permission_composition_store.go
// ============================================================

// RegisterpgPermissionCompositionStore registers the pg-permission-composition-store with the registry
// Auto-generated from annotations:
//   - @Service name="pg-permission-composition-store"
//   - @Inject annotations
func RegisterpgPermissionCompositionStore() {
	lokstra_registry.RegisterLazyService("pg-permission-composition-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &pgPermissionCompositionStore{
			dbPool: deps["@auth.db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "@auth.db_auth", },
	})
}


// ============================================================
// FILE: permission_store.go
// ============================================================

// RegisterpgPermissionStore registers the pg-permission-store with the registry
// Auto-generated from annotations:
//   - @Service name="pg-permission-store"
//   - @Inject annotations
func RegisterpgPermissionStore() {
	lokstra_registry.RegisterLazyService("pg-permission-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &pgPermissionStore{
			dbPool: deps["@auth.db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "@auth.db_auth", },
	})
}


// ============================================================
// FILE: policy_store.go
// ============================================================

// RegisterpgPolicyStore registers the pg-policy-store with the registry
// Auto-generated from annotations:
//   - @Service name="pg-policy-store"
//   - @Inject annotations
func RegisterpgPolicyStore() {
	lokstra_registry.RegisterLazyService("pg-policy-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &pgPolicyStore{
			dbPool: deps["@auth.db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "@auth.db_auth", },
	})
}


// ============================================================
// FILE: refresh_token_store.go
// ============================================================

// RegisterpgRefreshTokenStore registers the pg-refresh-token-store with the registry
// Auto-generated from annotations:
//   - @Service name="pg-refresh-token-store"
//   - @Inject annotations
func RegisterpgRefreshTokenStore() {
	lokstra_registry.RegisterLazyService("pg-refresh-token-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &pgRefreshTokenStore{
			dbPool: deps["@auth.db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "@auth.db_auth", },
	})
}


// ============================================================
// FILE: role_permission_store.go
// ============================================================

// RegisterpgRolePermissionStore registers the pg-role-permission-store with the registry
// Auto-generated from annotations:
//   - @Service name="pg-role-permission-store"
//   - @Inject annotations
func RegisterpgRolePermissionStore() {
	lokstra_registry.RegisterLazyService("pg-role-permission-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &pgRolePermissionStore{
			dbPool: deps["@auth.db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "@auth.db_auth", },
	})
}


// ============================================================
// FILE: role_store.go
// ============================================================

// RegisterpgRoleStore registers the pg-role-store with the registry
// Auto-generated from annotations:
//   - @Service name="pg-role-store"
//   - @Inject annotations
func RegisterpgRoleStore() {
	lokstra_registry.RegisterLazyService("pg-role-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &pgRoleStore{
			dbPool: deps["@auth.db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "@auth.db_auth", },
	})
}


// ============================================================
// FILE: session_store.go
// ============================================================

// RegisterpgSessionStore registers the pg-session-store with the registry
// Auto-generated from annotations:
//   - @Service name="pg-session-store"
//   - @Inject annotations
func RegisterpgSessionStore() {
	lokstra_registry.RegisterLazyService("pg-session-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &pgSessionStore{
			dbPool: deps["@auth.db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "@auth.db_auth", },
	})
}


// ============================================================
// FILE: tenant_store.go
// ============================================================

// RegisterpgTenantStore registers the pg-tenant-store with the registry
// Auto-generated from annotations:
//   - @Service name="pg-tenant-store"
//   - @Inject annotations
func RegisterpgTenantStore() {
	lokstra_registry.RegisterLazyService("pg-tenant-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &pgTenantStore{
			dbPool: deps["@auth.db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "@auth.db_auth", },
	})
}


// ============================================================
// FILE: user_app_store.go
// ============================================================

// RegisterpgUserAppStore registers the pg-user-app-store with the registry
// Auto-generated from annotations:
//   - @Service name="pg-user-app-store"
//   - @Inject annotations
func RegisterpgUserAppStore() {
	lokstra_registry.RegisterLazyService("pg-user-app-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &pgUserAppStore{
			dbPool: deps["@auth.db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "@auth.db_auth", },
	})
}


// ============================================================
// FILE: user_identity_store.go
// ============================================================

// RegisterpgUserIdentityStore registers the pg-user-identity-store with the registry
// Auto-generated from annotations:
//   - @Service name="pg-user-identity-store"
//   - @Inject annotations
func RegisterpgUserIdentityStore() {
	lokstra_registry.RegisterLazyService("pg-user-identity-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &pgUserIdentityStore{
			dbPool: deps["@auth.db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "@auth.db_auth", },
	})
}


// ============================================================
// FILE: user_permission_store.go
// ============================================================

// RegisterpgUserPermissionStore registers the pg-user-permission-store with the registry
// Auto-generated from annotations:
//   - @Service name="pg-user-permission-store"
//   - @Inject annotations
func RegisterpgUserPermissionStore() {
	lokstra_registry.RegisterLazyService("pg-user-permission-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &pgUserPermissionStore{
			dbPool: deps["@auth.db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "@auth.db_auth", },
	})
}


// ============================================================
// FILE: user_role_store.go
// ============================================================

// RegisterpgUserRoleStore registers the pg-user-role-store with the registry
// Auto-generated from annotations:
//   - @Service name="pg-user-role-store"
//   - @Inject annotations
func RegisterpgUserRoleStore() {
	lokstra_registry.RegisterLazyService("pg-user-role-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &pgUserRoleStore{
			dbPool: deps["@auth.db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "@auth.db_auth", },
	})
}


// ============================================================
// FILE: user_store.go
// ============================================================

// RegisterpgUserStore registers the pg-user-store with the registry
// Auto-generated from annotations:
//   - @Service name="pg-user-store"
//   - @Inject annotations
func RegisterpgUserStore() {
	lokstra_registry.RegisterLazyService("pg-user-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &pgUserStore{
			dbPool: deps["@auth.db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "@auth.db_auth", },
	})
}


